# Generated by Django 6.0.6 on 2026-06-13 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#6366F1', max_length=20)),
                ('volume', models.IntegerField(choices=[(1, 'Volume One'), (2, 'Volume Two')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True)),
                ('standard', models.CharField(blank=True, max_length=200)),
                ('bss', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='standards.nccnode')),
            ],
            options={
                'verbose_name': 'NCC Node',
                'verbose_name_plural': 'NCC Nodes',
                'ordering': ['volume', 'order'],
            },
        ),
    ]
