# Generated by Django 6.0.6 on 2026-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_nccnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccnode',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nccnode',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nccnode',
            name='why',
            field=models.TextField(blank=True),
        ),
    ]
