# Generated by Django 6.0.6 on 2026-06-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_nccnode_example_nccnode_photo_url_nccnode_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccnode',
            name='calculator_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
