SECTION_G = {
    "id": "G",
    "title": "Section G",
    "subtitle": "Ancillary provisions",
    "color": "#888780",
    "children": [
        {
            "id": "G1",
            "title": "Part G1",
            "subtitle": "Minor structures",
            "color": "#888780",
            "children": [
                {
                    "id": "G1-O",
                    "title": "G1O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G1-D",
                    "title": "G1D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                },
            ],
        },
        {
            "id": "G2",
            "title": "Part G2",
            "subtitle": "Boilers, pressure vessels, heating appliances, fireplaces, chimneys and flues",
            "color": "#888780",
            "children": [
                {
                    "id": "G2-O",
                    "title": "G2O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G2-P",
                    "title": "G2P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "G2-D",
                    "title": "G2D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                    "desc": "Governs safe installation of boilers, pressure vessels, fireplaces and flues. Relevant to heating product selection and installation clearances.",
                },
            ],
        },
        {
            "id": "G3",
            "title": "Part G3",
            "subtitle": "Atrium construction",
            "color": "#888780",
            "children": [
                {
                    "id": "G3-O",
                    "title": "G3O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G3-P",
                    "title": "G3P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "G3-D",
                    "title": "G3D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                    "desc": "Sets out construction and fire safety requirements for buildings with atriums. Covers glazing, balustrades and smoke control relevant to product selection.",
                },
            ],
        },
        {
            "id": "G4",
            "title": "Part G4",
            "subtitle": "Construction in alpine areas",
            "color": "#888780",
            "children": [
                {
                    "id": "G4-O",
                    "title": "G4O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G4-P",
                    "title": "G4P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "G4-D",
                    "title": "G4D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                    "desc": "Additional requirements for buildings in alpine environments covering snow loads, insulation, and weatherproofing beyond standard requirements.",
                },
            ],
        },
        {
            "id": "G5",
            "title": "Part G5",
            "subtitle": "Construction in bushfire prone areas",
            "color": "#888780",
            "children": [
                {
                    "id": "G5-O",
                    "title": "G5O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G5-P",
                    "title": "G5P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "G5-D",
                    "title": "G5D1",
                    "subtitle": "DTS → AS 3959",
                    "color": "#888780",
                    "standard": "AS 3959",
                    "desc": "Buildings in bushfire prone areas must comply with AS 3959. BAL (Bushfire Attack Level) rating determines cladding, glazing, and sealing requirements.",
                },
            ],
        },
        {
            "id": "G6",
            "title": "Part G6",
            "subtitle": "Occupiable outdoor areas",
            "color": "#888780",
            "children": [
                {
                    "id": "G6-O",
                    "title": "G6O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G6-P",
                    "title": "G6P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "G6-D",
                    "title": "G6D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                    "desc": "Requirements for rooftop and podium outdoor areas used by occupants. Covers balustrades, waterproofing, drainage and surface finishes.",
                },
            ],
        },
        {
            "id": "G7",
            "title": "Part G7",
            "subtitle": "Livable housing design",
            "color": "#888780",
            "children": [
                {
                    "id": "G7-O",
                    "title": "G7O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "G7-P",
                    "title": "G7P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "G7-D",
                    "title": "G7D1",
                    "subtitle": "DTS → livable housing",
                    "color": "#888780",
                    "desc": "Accessible entry, step-free shower, wider doorways (820mm min clear) for livable housing design. Applies to new Class 2 and Class 1 buildings from 2022.",
                },
            ],
        },
        {
            "id": "G-S30",
            "title": "Specification 30",
            "subtitle": "Installation of boilers and pressure vessels",
            "color": "#888780",
            "desc": "Technical installation requirements for boilers and pressure vessels including clearances, flues and safety devices.",
        },
        {
            "id": "G-S31",
            "title": "Specification 31",
            "subtitle": "Fire and smoke control in buildings with atriums",
            "color": "#888780",
            "desc": "Engineering requirements for fire and smoke control systems in atrium buildings. Covers mechanical exhaust, detection and sprinkler provisions.",
        },
        {
            "id": "G-S43",
            "title": "Specification 43",
            "subtitle": "Bushfire protection for certain Class 9 buildings",
            "color": "#888780",
            "desc": "Construction requirements for Class 9 buildings in bushfire prone areas. Covers external wall cladding, glazing, vents and sealing requirements based on BAL rating.",
        },
    ],
}
