SECTION_E = {
    "id": "E",
    "title": "Section E",
    "subtitle": "Services",
    "color": "#888780",
    "children": [
        {
            "id": "E1",
            "title": "Part E1",
            "subtitle": "Fire fighting",
            "color": "#888780",
            "children": [
                {
                    "id": "E1-O",
                    "title": "E1O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "E1-P",
                    "title": "E1P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "E1-D",
                    "title": "E1D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                },
            ],
        },
        {
            "id": "E2",
            "title": "Part E2",
            "subtitle": "Smoke hazard",
            "color": "#888780",
            "children": [
                {
                    "id": "E2-O",
                    "title": "E2O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "E2-P",
                    "title": "E2P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "E2-D",
                    "title": "E2D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                },
            ],
        },
        {
            "id": "E3",
            "title": "Part E3",
            "subtitle": "Lift installations",
            "color": "#888780",
            "children": [
                {
                    "id": "E3-O",
                    "title": "E3O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "E3-P",
                    "title": "E3P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "E3-D",
                    "title": "E3D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                },
            ],
        },
        {
            "id": "E4",
            "title": "Part E4",
            "subtitle": "Visibility in an emergency",
            "color": "#888780",
            "children": [
                {
                    "id": "E4-O",
                    "title": "E4O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "E4-P",
                    "title": "E4P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "E4-D",
                    "title": "E4D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                },
            ],
        },
        {
            "id": "E-S17",
            "title": "Specification 17",
            "subtitle": "Fire sprinkler systems",
            "color": "#888780",
            "desc": "Covers design and installation requirements for automatic fire sprinkler systems. Applies to Class 2–9 buildings above certain heights and areas.",
        },
        {
            "id": "E-S18",
            "title": "Specification 18",
            "subtitle": "Class 2 and 3 buildings up to 25m",
            "color": "#888780",
            "desc": "Simplified sprinkler provisions for Class 2 and 3 residential buildings not exceeding 25m effective height.",
        },
        {
            "id": "E-S19",
            "title": "Specification 19",
            "subtitle": "Fire control centres",
            "color": "#888780",
            "desc": "Layout and equipment requirements for fire control centres in larger buildings. Covers signage, communications and access provisions.",
        },
        {
            "id": "E-S20",
            "title": "Specification 20",
            "subtitle": "Smoke detection and alarm systems",
            "color": "#888780",
            "desc": "Technical requirements for smoke detection and alarm installations. Relevant to product selection for detection devices and alarm sounders.",
        },
        {
            "id": "E-S21",
            "title": "Specification 21",
            "subtitle": "Smoke exhaust systems",
            "color": "#888780",
            "desc": "Engineering requirements for mechanical smoke exhaust systems in large enclosed spaces such as atria and shopping centres.",
        },
        {
            "id": "E-S22",
            "title": "Specification 22",
            "subtitle": "Smoke-and-heat vents",
            "color": "#888780",
            "desc": "Requirements for passive smoke-and-heat venting systems including vent sizing and placement in single-storey warehouses and factories.",
        },
        {
            "id": "E-S23",
            "title": "Specification 23",
            "subtitle": "Residential fire safety systems",
            "color": "#888780",
            "desc": "Outlines fire safety system requirements for residential buildings including smoke alarms, sprinklers and warning systems for Class 2 and 3 buildings.",
        },
        {
            "id": "E-S24",
            "title": "Specification 24",
            "subtitle": "Lift installations",
            "color": "#888780",
            "desc": "Technical requirements for lift installations in buildings. Covers fire service lifts, stretcher lifts and general passenger lifts.",
        },
        {
            "id": "E-S25",
            "title": "Specification 25",
            "subtitle": "Photoluminescent exit signs",
            "color": "#888780",
            "desc": "Performance and installation requirements for photoluminescent exit signs as an alternative to illuminated signs in certain building types.",
        },
    ],
}
