SECTION_J = {
    "id": "J",
    "title": "Section J",
    "subtitle": "Energy efficiency",
    "color": "#BA7517",
    "children": [
        {
            "id": "J1",
            "title": "Part J1",
            "subtitle": "Energy performance",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J1-O",
                    "title": "J1O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J1-P",
                    "title": "J1P1",
                    "subtitle": "Performance requirement",
                    "color": "#BA7517",
                },
                {
                    "id": "J1-D",
                    "title": "J1D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                },
            ],
        },
        {
            "id": "J2",
            "title": "Part J2",
            "subtitle": "Energy efficiency",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J2-O",
                    "title": "J2O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J2-D",
                    "title": "J2D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                },
            ],
        },
        {
            "id": "J3",
            "title": "Part J3",
            "subtitle": "Elemental provisions for Class 2 sole-occupancy units",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J3-O",
                    "title": "J3O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J3-P",
                    "title": "J3P1",
                    "subtitle": "Performance requirement",
                    "color": "#BA7517",
                },
                {
                    "id": "J3-D",
                    "title": "J3D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                    "desc": "Prescribes energy efficiency requirements for individual apartments in Class 2 buildings and Class 4 parts. Covers ceiling, wall and floor insulation, glazing and sealing.",
                },
            ],
        },
        {
            "id": "J4",
            "title": "Part J4",
            "subtitle": "Building fabric",
            "color": "#BA7517",
            "bss": True,
            "children": [
                {
                    "id": "J4-O",
                    "title": "J4O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                    "desc": "To reduce heating and cooling energy consumption by requiring the building envelope to achieve minimum thermal performance levels appropriate to the climate zone.",
                    "example": "A Class 5 office building in Brisbane (Climate Zone 2) must have roof insulation achieving at least R3.7 total R-value and walls achieving at least R1.4 — without this, air conditioning systems must work significantly harder to maintain comfort.",
                    "why": "Building fabric is the most cost-effective way to reduce energy consumption — insulation installed during construction is far cheaper than the lifetime energy cost of compensating for poor thermal performance with larger mechanical systems.",
                },
                {
                    "id": "J4-D3",
                    "title": "J4D3",
                    "subtitle": "Thermal construction — general",
                    "color": "#BA7517",
                    "standard": "AS/NZS 4859.1, AS/NZS 4859.2, Specification 36",
                    "desc": "Insulation must comply with AS/NZS 4859.1 and be installed to abut or overlap adjoining insulation, form a continuous barrier, and not affect services. Reflective insulation requires an airspace between reflective surface and lining. Bulk insulation must maintain position and thickness. Roof, ceiling, wall and floor materials have thermal properties listed in Specification 36. Total R-Value must be calculated per AS/NZS 4859.2 for roofs and floors, Specification 37 for wall-glazing, and Specification 39 for sub-floor spaces.",
                    "example": "R2.5 glasswool batts installed in a ceiling must be laid to abut each other with no gaps, must overlap the top plate of the wall by at least 50mm at the eaves, and must not compress the batts over electrical cables — compressed batts lose R-value.",
                    "why": "Installation quality is as important as product R-value — a perfectly rated batt installed with gaps, compression, or discontinuities can perform at a fraction of its rated R-value, defeating the purpose of the insulation requirement.",
                },
                {
                    "id": "J4-D4",
                    "title": "J4D4",
                    "subtitle": "Roof and ceiling R-values",
                    "color": "#BA7517",
                    "desc": "A roof or ceiling must achieve a Total R-Value of: R3.7 (downward heat flow) in climate zones 1–5; R3.2 (downward) in zone 6; R3.7 (upward heat flow) in zone 7; R4.8 (upward) in zone 8. In all zones except 8, the solar absorptance of the upper roof surface must not exceed 0.45 (light-coloured roof required).",
                    "example": "A warehouse in Brisbane (Zone 2) needs roof Total R-Value ≥ R3.7. A 100mm glasswool batt (R2.5) plus reflective foil sarking (R0.5) plus air films (R0.17 each) gives approximately Total R3.3 — insufficient. Adding a foil-faced rigid board provides the additional R-value needed.",
                    "why": "Roof is the highest heat gain/loss surface in most Australian buildings — 40–60% of a building's cooling load enters through the roof. The R3.7 minimum reflects the large payback on roof insulation investment.",
                    "calculator_type": "r_value",
                },
                {
                    "id": "J4-D6",
                    "title": "J4D6",
                    "subtitle": "Walls and glazing U-values",
                    "color": "#BA7517",
                    "standard": "Specification 37",
                    "desc": "Wall-glazing construction Total System U-Value must not exceed U2.0 for Class 2 common areas and Class 5–9b buildings. For Class 3, 9c and 9a ward areas: U1.1 in zones 1, 3, 4, 6, 7; U2.0 in zones 2, 5; U0.9 in zone 8. Display glazing maximum U5.8. Wall components must achieve minimum R1.0 where wall is less than 80% of wall-glazing construction area. Solar admittance limits apply per Tables J4D6b and J4D6c.",
                    "example": "A Class 5 office building external wall system with 30% glazing must have Total System U-Value ≤ 2.0. The wall component (70% of area) must achieve R1.0 minimum — typically 75mm glasswool batts in a steel stud wall provides approximately R1.8.",
                    "why": "U-value (the inverse of R-value) measures heat transfer rate — lower U-value means better insulating performance. Glazing has inherently high U-values, so the system U-value approach accounts for the combined wall and window performance rather than requiring each element separately.",
                },
                {
                    "id": "J4-D7",
                    "title": "J4D7",
                    "subtitle": "Floor R-values",
                    "color": "#BA7517",
                    "desc": "Floors must achieve the Total R-Value in Table J4D7. A slab-on-ground without in-slab heating/cooling is deemed to achieve R2.0 except in zone 8 and certain Class 3/9a/9b buildings in zone 7. Perimeter edge insulation of R1.0 is required for slab-on-ground in zone 8 and for any slab with in-slab heating or cooling — water-resistant insulation continuous from finished ground level to 300mm depth or full slab edge depth.",
                    "example": "A Class 5 office in Canberra (Zone 7) with an in-slab hydronic heating system must have R1.0 perimeter edge insulation — extruded polystyrene (XPS) board at least 50mm thick (R≈1.4) installed around the full slab perimeter to 300mm depth.",
                    "why": "Slab edges are thermal bridges that bypass roof and wall insulation — in-slab heating systems lose significant energy through uninsulated edges, and zone 8 slabs lose heat to frozen or very cold ground throughout winter.",
                },
                {
                    "id": "J4-S36",
                    "title": "Specification 36",
                    "subtitle": "Material thermal properties",
                    "color": "#BA7517",
                    "standard": "AS/NZS 4859.1",
                    "desc": "Lists thermal conductivity (W/m·K) for common construction materials and R-values for air films and airspaces. R-value of a material = thickness (m) ÷ thermal conductivity. Key values: concrete 200mm ≈ R0.12, brick 110mm ≈ R0.10, glasswool 90mm ≈ R2.1, glasswool 130mm ≈ R3.1, polyester 90mm ≈ R2.0, XPS 50mm ≈ R1.4, PIR 50mm ≈ R2.5, plasterboard 10mm ≈ R0.06, air film (still) ≈ R0.12 each surface.",
                    "example": "A wall assembly: external brick 110mm (R0.10) + 90mm glasswool batt (R2.1) + plasterboard 13mm (R0.08) + air films (R0.24 total) = Total R-Value ≈ R2.52. This exceeds the R1.4 minimum for zones 1–6 but may not meet R2.8 for zone 7.",
                    "why": "Specification 36 provides the agreed thermal property values for DTS compliance calculations — using manufacturer-claimed values without reference to Specification 36 is not permitted for DTS compliance purposes.",
                },
            ],
        },
        {
            "id": "J5",
            "title": "Part J5",
            "subtitle": "Building sealing",
            "color": "#BA7517",
            "bss": True,
            "children": [
                {
                    "id": "J5-O",
                    "title": "J5O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                    "desc": "To reduce energy consumption of air-conditioning systems and improve thermal comfort by sealing the building envelope against uncontrolled air infiltration.",
                    "example": "A Class 5 office building with gaps around window frames, door perimeters and ceiling penetrations will lose conditioned air continuously — sealing these paths reduces the air conditioning load and improves occupant comfort.",
                    "why": "Air infiltration accounts for 15–25% of heating and cooling energy in commercial buildings — sealing is one of the cheapest energy efficiency measures available and directly impacts the sizing and running cost of mechanical systems.",
                },
                {
                    "id": "J5-D1",
                    "title": "J5D1",
                    "subtitle": "Deemed-to-Satisfy provisions",
                    "color": "#BA7517",
                    "desc": "Where a DTS Solution is proposed, Performance Requirements J1P1–J1P4 are satisfied by complying with J5D2–J5D8 as part of the full Section J DTS package.",
                    "example": "A Class 6 retail building complies with J5 by sealing all windows and doors, fitting exhaust fans with self-closing dampers, sealing ceiling/wall junctions, and providing an airlock at the main entrance to the conditioned space.",
                    "why": "J5D1 confirms sealing is a mandatory part of the DTS energy efficiency package — it cannot be omitted even if the insulation (J4) and glazing requirements are met.",
                },
                {
                    "id": "J5-D2",
                    "title": "J5D2",
                    "subtitle": "Application",
                    "color": "#BA7517",
                    "desc": "J5 applies to elements forming the envelope of Class 2–9 buildings. Exemptions: buildings in climate zones 1, 2, 3 and 5 where the only air-conditioning is evaporative cooling; permanent openings required for safe operation of gas appliances; and buildings where mechanical ventilation provides sufficient pressurisation to prevent infiltration.",
                    "example": "A Darwin (Zone 1) office building that uses only evaporative coolers for air-conditioning is exempt from J5 sealing requirements — evaporative coolers require air movement and sealing would prevent their operation.",
                    "why": "Evaporative coolers work by passing air through wet pads — they require openings for air flow and cannot function in a sealed building. The exemption prevents the sealing requirements from conflicting with the ventilation requirements of the cooling system.",
                },
                {
                    "id": "J5-D3",
                    "title": "J5D3–J5D4",
                    "subtitle": "Chimneys, flues and roof lights",
                    "color": "#BA7517",
                    "desc": "The chimney or flue of an open solid-fuel burning appliance must have a damper or flap to seal it when not in use. Roof lights must be sealed or capable of being sealed when serving a conditioned space or a habitable room in climate zones 4, 5, 6, 7 or 8 — using an imperforate ceiling diffuser, weatherproof seal, or operable shutter system.",
                    "example": "A Class 5 office building in Melbourne (Zone 6) with a roof light above a boardroom must have the roof light fitted with a sealed ceiling diffuser or a motorised blind/shutter system — an open-frame skylight with no sealing capability does not comply.",
                    "why": "Unsealed roof lights and chimneys are major air leakage paths — a single unsealed skylight can negate the energy savings from insulating an entire ceiling area in cooler climate zones.",
                },
                {
                    "id": "J5-D5",
                    "title": "J5D5",
                    "subtitle": "Windows, doors and building entrances",
                    "color": "#BA7517",
                    "desc": "Doors and openable windows forming part of the building envelope must be sealed. Door bottoms require a draft protection device; other edges require foam/rubber compression strip, fibrous seal or similar. Windows complying with AS 2047, fire doors, smoke doors, and security-only roller shutters are exempt. Building entrances leading to conditioned spaces must have an airlock, self-closing door, rapid roller door or revolving door — unless the conditioned space is ≤50m² or the entrance is an open-front café/restaurant with a 3m unconditioned zone.",
                    "example": "A Class 5 office building main entry leading to an air-conditioned lobby must have either a double-door airlock or self-closing doors — a single propped-open door is not compliant. A loading dock entrance to a refrigerated warehouse must have a rapid roller door.",
                    "why": "Building entrances are the largest uncontrolled air leakage path in commercial buildings — every time a single door opens to a conditioned space, a large volume of conditioned air escapes and is replaced by outside air that must be re-conditioned.",
                },
                {
                    "id": "J5-D6",
                    "title": "J5D6",
                    "subtitle": "Exhaust fans",
                    "color": "#BA7517",
                    "desc": "Exhaust fans must be fitted with a sealing device such as a self-closing damper when serving a conditioned space or a habitable room in climate zones 4, 5, 6, 7 or 8.",
                    "example": "A toilet exhaust fan in a Class 5 office building must have a self-closing damper that seals the duct when the fan is not operating — without it, outside air infiltrates through the fan duct whenever the fan is off, bypassing all wall insulation and sealing at that point.",
                    "why": "Exhaust fan openings are direct holes through the building envelope — a standard exhaust fan without a damper is equivalent to leaving a hole in the wall when the fan is not running.",
                },
                {
                    "id": "J5-D7",
                    "title": "J5D7",
                    "subtitle": "Construction of ceilings, walls and floors",
                    "color": "#BA7517",
                    "desc": "Ceilings, walls, floors and all opening frames must be constructed to minimise air leakage when forming part of the envelope or in climate zones 4–8. Construction must use internal lining systems close-fitting at ceiling, wall and floor junctions, or sealed at junctions and penetrations with architrave, skirting, cornice, expanding foam, rubber compressible strip, caulking or similar. Does not apply to openings required for smoke hazard management.",
                    "example": "In a Class 5 office building in Sydney (Zone 5), the perimeter of every window frame must be sealed with expanding foam or caulking between the frame and the wall framing. The ceiling/wall junction must have cornice or caulking. Every electrical penetration through the ceiling must be sealed.",
                    "why": "Diffuse air leakage through junctions and penetrations is harder to detect than obvious gaps but collectively accounts for more energy loss than individual unsealed openings — systematic sealing of all junctions is required, not just obvious gaps.",
                },
                {
                    "id": "J5-D8",
                    "title": "J5D8",
                    "subtitle": "Evaporative coolers",
                    "color": "#BA7517",
                    "desc": "An evaporative cooler must be fitted with a self-closing damper or similar when serving a heated space or in climate zones 4, 5, 6, 7 or 8.",
                    "example": "A ducted evaporative cooler on a Class 6 shop in Adelaide (Zone 6) must have a self-closing damper on the unit — in winter when the cooler is not operating, the damper must seal the opening to prevent cold outside air from entering the building through the cooler.",
                    "why": "Evaporative coolers have large inlet and outlet openings — without a damper, they act as a direct uninsulated hole through the roof connecting inside and outside air, negating all ceiling insulation in the vicinity of the unit.",
                },
            ],
        },
        {
            "id": "J6",
            "title": "Part J6",
            "subtitle": "Air-conditioning and ventilation",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J6-O",
                    "title": "J6O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J6-D",
                    "title": "J6D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                },
            ],
        },
        {
            "id": "J7",
            "title": "Part J7",
            "subtitle": "Artificial lighting and power",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J7-O",
                    "title": "J7O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J7-D",
                    "title": "J7D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                },
            ],
        },
        {
            "id": "J8",
            "title": "Part J8",
            "subtitle": "Heated water supply",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J8-O",
                    "title": "J8O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J8-D",
                    "title": "J8D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                },
            ],
        },
        {
            "id": "J9",
            "title": "Part J9",
            "subtitle": "Energy monitoring",
            "color": "#BA7517",
            "children": [
                {
                    "id": "J9-O",
                    "title": "J9O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "J9-D",
                    "title": "J9D1",
                    "subtitle": "DTS solution",
                    "color": "#BA7517",
                },
            ],
        },
        {
            "id": "J-S33",
            "title": "Specification 33",
            "subtitle": "Additional requirements",
            "color": "#BA7517",
            "desc": "Supplementary energy efficiency requirements applying to specific building types and climate zones beyond the standard J-section provisions.",
        },
        {
            "id": "J-S34",
            "title": "Specification 34",
            "subtitle": "Modelling parameters for J1V3",
            "color": "#BA7517",
            "desc": "Input parameters and assumptions for whole-building energy modelling under the J1V3 verification pathway. Used by energy assessors for commercial buildings.",
        },
        {
            "id": "J-S35",
            "title": "Specification 35",
            "subtitle": "Modelling profiles for J1V3",
            "color": "#BA7517",
            "desc": "Operational profiles used in energy modelling including occupancy schedules, lighting density and equipment loads for different building uses.",
        },
        {
            "id": "J-S36",
            "title": "Specification 36",
            "subtitle": "Material properties",
            "color": "#BA7517",
            "desc": "Thermal properties of common building materials including R-values, U-values and solar absorptance. Key reference for insulation and glazing product selection.",
        },
        {
            "id": "J-S37",
            "title": "Specification 37",
            "subtitle": "Calculation of U-Value and solar admittance",
            "color": "#BA7517",
            "desc": "Methodology for calculating U-Value and solar admittance of glazing and window systems. Relevant to window and glazing product selection for energy compliance.",
        },
        {
            "id": "J-S38",
            "title": "Specification 38",
            "subtitle": "Spandrel panel thermal performance",
            "color": "#BA7517",
            "desc": "Calculation method for determining thermal performance of spandrel panels in commercial facade systems.",
        },
        {
            "id": "J-S39",
            "title": "Specification 39",
            "subtitle": "Sub-floor and soil thermal performance",
            "color": "#BA7517",
            "desc": "Method for calculating thermal resistance of sub-floor spaces and soil conditions for ground floor energy modelling.",
        },
        {
            "id": "J-S40",
            "title": "Specification 40",
            "subtitle": "Lighting and power control devices",
            "color": "#BA7517",
            "desc": "Requirements for lighting control systems including occupancy sensors, daylight dimming and time switches. Relevant to lighting product selection for commercial fitouts.",
        },
        {
            "id": "J-S44",
            "title": "Specification 44",
            "subtitle": "Calculation of heating, cooling and thermal energy load limits",
            "color": "#BA7517",
            "desc": "Defines the calculation methodology for determining heating load limits, cooling load limits and thermal energy load limits for Class 2 sole-occupancy units.",
        },
        {
            "id": "J-S45",
            "title": "Specification 45",
            "subtitle": "Modelling profiles for J1V5",
            "color": "#BA7517",
            "desc": "Operational profiles for the J1V5 whole-of-home energy verification method for Class 2 apartments. Covers occupancy, lighting and appliance schedules.",
        },
    ],
}
