# NCC Volume One — Section B: Structure

SECTION_B = {
    "id": "B",
    "title": "Section B",
    "subtitle": "Structure",
    "color": "#888780",
    "children": [
        {
            "id": "B1",
            "title": "Part B1",
            "subtitle": "Structural provisions",
            "color": "#888780",
            "children": [
                # ── Objective ─────────────────────────────────────────────
                {
                    "id": "B1-O",
                    "title": "B1O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                    "desc": "To safeguard people from injury caused by structural failure, loss of amenity caused by structural behaviour, protect other property from physical damage caused by structural failure, and safeguard people from injury caused by failure of or impact with glazing.",
                    "example": "A multi-storey office building must be designed so floors, columns and beams do not collapse under occupancy loads, wind or earthquake forces, and all glazing must be safety glass in locations where human impact is possible.",
                    "why": "Buildings must remain standing and glazing must not injure occupants under all foreseeable conditions — structural and glazing failures are among the most catastrophic building defects.",
                },
                # ── Functional Statements ──────────────────────────────────
                {
                    "id": "B1-F1",
                    "title": "B1F1",
                    "subtitle": "Structure",
                    "color": "#888780",
                    "desc": "A building or structure is to withstand the combination of loads and other actions to which it may be reasonably subjected.",
                    "example": "A roof must carry its own self-weight plus rain, wind uplift, maintenance loads and any mechanical plant — all acting simultaneously in the worst credible combination.",
                    "why": "Structural elements are always subjected to multiple simultaneous loads; the functional statement ensures design accounts for realistic combinations, not just single loads in isolation.",
                },
                {
                    "id": "B1-F2",
                    "title": "B1F2",
                    "subtitle": "Glazing",
                    "color": "#888780",
                    "desc": "Glazing is to be installed in a building to avoid undue risk of injury to people. Glazing in a building should not cause injury due to its failure or because people impacted with it because they did not see it.",
                    "example": "A full-height glass panel beside a building entrance must use safety glass (toughened or laminated) and include manifestation markings at eye level so people can see the glass before walking into it.",
                    "why": "Clear glass is invisible to approaching people — unmarked or non-safety glass panels near walkways and doors cause serious lacerations when impacted.",
                },
                # ── Performance Requirements ───────────────────────────────
                {
                    "id": "B1-P1",
                    "title": "B1P1",
                    "subtitle": "Structural reliability",
                    "color": "#888780",
                    "desc": "A building or structure must, with appropriate degrees of reliability, perform adequately under all reasonably expected design actions, withstand extreme or frequently repeated design actions, be designed to sustain local damage without disproportionate collapse, and avoid causing damage to other properties. Actions include permanent, imposed, wind, earthquake, snow, liquid pressure, ground water, rainwater, earth pressure, differential movement, creep, shrinkage, thermal effects, ground movement and termite actions.",
                    "example": "A shopping centre must be designed so that if one column is damaged (e.g. by a vehicle impact), the floors above do not progressively collapse — the structure redistributes load to adjacent columns.",
                    "why": "Progressive collapse — where local failure triggers a chain reaction — is responsible for some of the worst building disasters. B1P1 requires robustness by design, not just strength.",
                },
                {
                    "id": "B1-P2",
                    "title": "B1P2",
                    "subtitle": "Structural resistance",
                    "color": "#888780",
                    "desc": "The structural resistance of materials and forms of construction must be determined using five percentile characteristic material properties with appropriate allowance for construction activities, type of material, site characteristics, accuracy of assessment methods, and action effects from differential settlement and restrained dimensional changes.",
                    "example": "Concrete compressive strength used in design must be the characteristic value (f'c) — the value exceeded by 95% of test specimens — not the mean strength. A 32 MPa specified concrete uses f'c = 32 MPa in calculations even though average cylinder strength may be 38 MPa.",
                    "why": "Using mean material properties would mean half of all elements are weaker than designed — five percentile values ensure the vast majority of constructed elements meet or exceed design assumptions.",
                },
                {
                    "id": "B1-P3",
                    "title": "B1P3",
                    "subtitle": "Glass installations at risk of human impact",
                    "color": "#888780",
                    "desc": "Glass installations at risk of human impact must have glazing that breaks in a way not likely to cause injury, resists reasonably foreseeable human impact without breaking, or is protected or marked to reduce the likelihood of human impact.",
                    "example": "Shower screen glass must be toughened safety glass (AS/NZS 2208) — when broken it shatters into small blunt pieces rather than large sharp shards. A frameless glass balustrade must be laminated glass so broken panels remain in place rather than falling.",
                    "why": "Ordinary annealed glass breaks into large razor-sharp shards that cause severe lacerations — safety glazing requirements in human impact zones have dramatically reduced glass-related injuries.",
                },
                {
                    "id": "B1-P4",
                    "title": "B1P4",
                    "subtitle": "Buildings in flood areas",
                    "color": "#888780",
                    "desc": "A building in a flood hazard area must be designed and constructed to resist flotation, collapse or significant permanent movement from hydrostatic, hydrodynamic, erosion and scour, wind and other actions during the defined flood event. Applies to Class 2, 3, 4, 9a and 9c buildings.",
                    "example": "A Class 2 apartment building in a flood-prone riverside area must have ground floor structure designed to resist floodwater pressure and uplift, with floor levels elevated above the defined flood level or flood-resistant materials used below that level.",
                    "why": "Floodwater exerts enormous hydrostatic and hydrodynamic forces — buildings not designed for these loads can float off foundations, collapse walls, or suffer irreparable structural damage in a single flood event.",
                },
                # ── Verification Methods ───────────────────────────────────
                {
                    "id": "B1-V1",
                    "title": "B1V1",
                    "subtitle": "Structural reliability (β index)",
                    "color": "#888780",
                    "standard": "AS/NZS 1170.0",
                    "desc": "Verifies compliance with B1P1 and B1P2 for structural components using the reliability index β. Applicable to components with resistance coefficient of variation between 10% and 40%. A component passes when β meets or exceeds the target reliability index from Table B1V1b. The equation is: β = ln[(R̄/S̄)√(CS/CR)] / √ln(CR·CS) where CR = 1+VR² and CS = 1+VS².",
                    "example": "An engineer proposes a non-standard steel connection. They test samples to establish mean resistance R̄ = 150 kN and coefficient of variation VR = 15%. The governing load has mean S̄ = 60 kN and VS = 20%. Use the calculator below to determine if β ≥ target.",
                    "why": "B1V1 allows engineers to demonstrate compliance for innovative or non-standard structural solutions that cannot be directly assessed against prescriptive DTS tables — it is the primary Performance Solution pathway for structural components.",
                    "calculator_type": "b1v1",
                },
                {
                    "id": "B1-V2",
                    "title": "B1V2",
                    "subtitle": "Structural robustness",
                    "color": "#888780",
                    "desc": "Verifies compliance with B1P1(1)(c) for structural robustness. The structure must remain stable and collapse must not extend beyond immediately adjacent storeys upon notional removal of any single column, any beam supporting one or more columns, or any load-bearing wall segment of length equal to wall height. If any component carries more than 25% of total structural load, a systematic risk assessment must be undertaken.",
                    "example": "A 10-storey concrete frame building must be analysed with each ground floor column removed in turn. The analysis must show that removal of any single column causes at most localised failure — not progressive collapse of multiple floors above.",
                    "why": "The 25% threshold identifies single points of failure — components that carry a disproportionate share of load are high-risk elements that need either redundancy or explicit hazard mitigation.",
                },
                # ── DTS Provisions ────────────────────────────────────────
                {
                    "id": "B1-D1",
                    "title": "B1D1",
                    "subtitle": "Deemed-to-Satisfy provisions",
                    "color": "#888780",
                    "desc": "Where a DTS Solution is proposed, Performance Requirements B1P1 to B1P4 are satisfied by complying with B1D2 to B1D6. Where a Performance Solution is proposed, relevant Performance Requirements must be determined in accordance with A2G2(3) and A2G4(3).",
                    "example": "A standard residential project follows B1D2 (load combinations), B1D3 (individual actions from AS/NZS 1170 series), and B1D4 (material standards like AS 3600 for concrete and AS 4100 for steel) to satisfy all structural performance requirements without needing a Performance Solution.",
                    "why": "B1D1 is the gateway clause — it maps performance requirements to their corresponding DTS clauses, making it clear which clauses must be satisfied for a compliant DTS structural solution.",
                },
                {
                    "id": "B1-D2",
                    "title": "B1D2",
                    "subtitle": "Resistance to actions",
                    "color": "#888780",
                    "standard": "AS/NZS 1170.0",
                    "desc": "The resistance of a building or structure must be greater than the most critical action effect from different combinations of actions. The most critical action effect is determined in accordance with B1D3 and AS/NZS 1170.0 general design procedures. Resistance is determined in accordance with B1D4.",
                    "example": "A steel beam must be checked for the worst combination of 1.2G + 1.5Q (dead plus live) and 1.2G + Wu (dead plus wind uplift). The beam's design capacity from AS 4100 must exceed the maximum action effect from either combination.",
                    "why": "Different load combinations govern different failure modes — checking only one combination misses the case that actually controls design.",
                },
                {
                    "id": "B1-D3",
                    "title": "B1D3",
                    "subtitle": "Determination of individual actions",
                    "color": "#888780",
                    "standard": "AS/NZS 1170.1, AS/NZS 1170.2, AS/NZS 1170.3, AS 1170.4",
                    "desc": "Individual actions must be determined from: permanent actions (self-weight + AS/NZS 1170.1, plus 0.15 kPa notional roof load for Class 7b buildings for solar panels); imposed actions (occupancy loads per AS/NZS 1170.1); wind, snow and earthquake actions (AS/NZS 1170.2, 1170.3, AS 1170.4 based on Importance Level); and other actions including liquid pressure, groundwater, rainwater ponding, earth pressure, differential movement, creep, shrinkage, thermal effects and ground movement.",
                    "example": "A Class 5 office building in Brisbane (Wind Region B, Importance Level 2): permanent actions from AS/NZS 1170.1 self-weight tables, imposed floor loads 3.0 kPa from Table 3.1, wind from AS/NZS 1170.2 for Region B, earthquake from AS 1170.4 using Z = 0.08 for Brisbane.",
                    "why": "Every action type must be explicitly quantified from the appropriate source — designers cannot estimate or assume loads without reference to the AS/NZS 1170 series.",
                },
                {
                    "id": "B1-D4",
                    "title": "B1D4",
                    "subtitle": "Structural resistance of materials",
                    "color": "#888780",
                    "standard": "AS 3700, AS 3600, AS 4100, AS 1720.1, AS 1288, AS 2047, AS 3660.1",
                    "desc": "Structural resistance must be determined per the relevant material standard: masonry (AS 3700), concrete including reinforced, prestressed and AAC (AS 3600, AS 5146), steel including cold-formed and composite (AS 4100, AS/NZS 4600, AS/NZS 2327), aluminium (AS/NZS 1664), timber (AS 1720.1, AS 1684), piling (AS 2159), glazed assemblies in external walls (AS 2047), all other glazing (AS 1288), termite risk management (AS 3660.1), roof construction including tiling and metal roofing (AS 2050, AS 1562.1), and cyclonic garage doors (AS/NZS 4505).",
                    "example": "A concrete column is designed to AS 3600 using f'c = 40 MPa. External windows are rated per AS 2047 to N3 wind pressure. Shower screens comply with AS 1288 using 6mm toughened safety glass. Subfloor timber framing uses AS 3660.1 compliant termite management.",
                    "why": "Each material and product type has a dedicated Australian Standard that encodes decades of research and failure analysis — B1D4 ensures the right standard is applied to each element type.",
                },
                {
                    "id": "B1-D5",
                    "title": "B1D5",
                    "subtitle": "Structural software",
                    "color": "#888780",
                    "desc": "Structural software for DTS design of steel or timber trussed roof/floor systems and framed building systems must comply with the ABCB Protocol for Structural Software. Geometric limits apply: eaves height ≤ 6m, roof height ≤ 8.5m, building width ≤ 16m, length ≤ 5× width, roof pitch ≤ 35°. Does not apply to individual frame member design tables similar to AS 1684 or NASH Standard Part 2.",
                    "example": "A truss design software package used to design roof trusses for a Class 2 apartment building must be certified under the ABCB Protocol. The building is 12m wide (≤16m) and trusses span at 10° pitch (≤35°) — software is applicable. A simple AS 1684 span table lookup does not require Protocol compliance.",
                    "why": "Structural software that silently applies incorrect load combinations or material properties can produce compliant-looking but unsafe designs — the ABCB Protocol ensures software is validated before being used for DTS compliance.",
                },
                {
                    "id": "B1-D6",
                    "title": "B1D6",
                    "subtitle": "Construction in flood hazard areas",
                    "color": "#888780",
                    "desc": "Buildings in flood hazard areas must comply with the ABCB Standard for Construction of Buildings in Flood Hazard Areas. Applies only to Class 2, 3, 9a, 9c buildings and Class 4 parts of buildings.",
                    "example": "A Class 3 serviced apartment building identified in a council flood overlay must have its lowest habitable floor level set above the defined flood level, with flood-resistant materials below that level, and structural connections designed to resist hydrostatic uplift forces.",
                    "why": "Standard construction practices assume dry conditions — flood actions (uplift, lateral water pressure, debris impact, scour) require specific design responses that are not captured in the general structural provisions.",
                },
            ],
        },
        {
            "id": "B-S4",
            "title": "Specification 4",
            "subtitle": "Design of buildings in cyclonic areas",
            "color": "#888780",
            "standard": "AS/NZS 1170.2, AS 4055",
            "desc": "Applies to buildings in Wind Regions C and D (cyclonic — coastal QLD, WA, NT). All structural elements and building envelope products including windows, doors, roofing, wall cladding, and fixings must meet cyclonic wind ratings. Metal roof cladding, its connections and immediate supporting members must comply with this specification.",
            "example": "A school in Townsville (Wind Region C) requires windows tested to AS 2047 at cyclonic pressure levels, roofing with cyclonic-rated fasteners at increased fixing frequency, and garage doors with AS/NZS 4505 cyclonic bracing kits.",
            "why": "Tropical cyclones generate wind pressures far exceeding non-cyclonic design loads — standard products rated for non-cyclonic regions will fail, turning building components into dangerous projectiles.",
        },
    ],
}
