# NCC Volume One — Section C: Fire Resistance

SECTION_C = {
    "id": "C",
    "title": "Section C",
    "subtitle": "Fire resistance",
    "color": "#E24B4A",
    "children": [
        {
            "id": "C1",
            "title": "Part C1",
            "subtitle": "Fire resistance",
            "color": "#E24B4A",
            "children": [
                # ── Objective ─────────────────────────────────────────────
                {
                    "id": "C1-O",
                    "title": "C1O1",
                    "subtitle": "Objective",
                    "color": "#E24B4A",
                    "desc": "The objective of Parts C1–C4 is to safeguard people from illness or injury due to fire, safeguard occupants while evacuating, facilitate emergency services activities, avoid spread of fire between buildings, and protect other property from physical damage caused by structural failure due to fire.",
                    "example": "A Class 5 office building must be designed so that if a fire starts in one tenancy, structural elements remain standing long enough for all occupants to evacuate, fire does not spread to adjacent buildings, and firefighters can safely enter and operate.",
                    "why": "Fire is the most lethal building hazard — the objective explicitly covers all four failure modes: injury during fire, injury during evacuation, fire spread between buildings, and structural collapse from fire.",
                },
                # ── Functional Statements ──────────────────────────────────
                {
                    "id": "C1-F1",
                    "title": "C1F1",
                    "subtitle": "Structural stability during a fire",
                    "color": "#E24B4A",
                    "desc": "A building is to be constructed to maintain structural stability during fire to allow occupants time to evacuate safely, allow for fire brigade intervention, and avoid damage to other property.",
                    "example": "A concrete-framed office building must maintain column and beam integrity for the duration of the fire resistance level (FRL) period — typically 90–120 minutes for mid-rise buildings — so occupants can evacuate and firefighters can operate safely.",
                    "why": "Structural collapse during a fire is fatal for both occupants still in the building and firefighters conducting search and rescue — FRL requirements are calibrated to the time needed for safe evacuation and fire brigade intervention.",
                },
                {
                    "id": "C1-F2",
                    "title": "C1F2",
                    "subtitle": "Prevention of fire spread",
                    "color": "#E24B4A",
                    "desc": "A building is to be provided with safeguards to prevent fire spread so occupants have time to evacuate, to allow fire brigade intervention, to sole-occupancy units providing sleeping accommodation (Class 2, 3, 4), to adjoining fire compartments, and between buildings.",
                    "example": "In a Class 2 apartment building, fire-rated walls and floors between apartments must prevent fire spreading from a burning apartment to sleeping residents in adjacent apartments, giving them time to be alerted and evacuate.",
                    "why": "People in sleeping accommodation have reduced awareness of fire — fire spread prevention to sole-occupancy units is specifically required for Class 2, 3 and 4 buildings because occupants may be asleep when a fire starts.",
                },
                # ── Performance Requirements ───────────────────────────────
                {
                    "id": "C1-P1",
                    "title": "C1P1",
                    "subtitle": "Structural stability during a fire",
                    "color": "#E24B4A",
                    "desc": "A building must have elements that maintain structural stability during fire appropriate to the function/use, fire load, potential fire intensity, fire hazard, building height, proximity to other property, active fire safety systems, fire compartment size, fire brigade intervention capability, elements they support, and evacuation time.",
                    "example": "A 25-storey Class 2 apartment building requires Type A fire-resisting construction with FRL 120/120/120 for columns and loadbearing walls — because building height, evacuation time, and fire load all demand longer structural integrity than a 3-storey building.",
                    "why": "FRL requirements increase with building height and complexity because evacuation takes longer, fire brigade access is harder, and the consequences of structural failure are more severe in taller buildings.",
                },
                {
                    "id": "C1-P2",
                    "title": "C1P2",
                    "subtitle": "Spread of fire",
                    "color": "#E24B4A",
                    "desc": "A building must have elements that avoid spread of fire to exits, to sole-occupancy units and public corridors (Class 2, 3, 4 only), between buildings, and within a building. Avoidance must be appropriate to building function, fire load, fire intensity, fire hazard, number of storeys, proximity to other property, active fire systems, compartment size, fire brigade intervention, and evacuation time.",
                    "example": "A shopping centre must have fire-rated construction separating tenancies so a fire in one shop does not spread to exit corridors or adjacent shops within the FRL period. External wall systems must prevent fire radiating to neighbouring buildings on adjacent allotments.",
                    "why": "Fire spread to exits is the most dangerous outcome — trapped occupants with no escape route face near-certain death. Compartmentation buys critical time for evacuation before exits become untenable.",
                },
                {
                    "id": "C1-P3",
                    "title": "C1P3",
                    "subtitle": "Spread of fire and smoke in health and residential care buildings",
                    "color": "#E24B4A",
                    "desc": "A building must be protected from spread of fire and smoke to allow sufficient time for orderly evacuation. Applies only to patient care areas of Class 9a health-care buildings and Class 9c buildings.",
                    "example": "A hospital ward (Class 9a) must have smoke-proof walls between patient bays and corridors so that a fire in one bay can be contained while non-ambulant patients are moved horizontally to a safe area on the same floor rather than attempting stair evacuation.",
                    "why": "Patients in hospitals and aged care facilities cannot self-evacuate — the defend-in-place strategy requires much higher fire and smoke containment than standard buildings to allow staff-assisted horizontal evacuation.",
                },
                {
                    "id": "C1-P4",
                    "title": "C1P4",
                    "subtitle": "Safe conditions for evacuation",
                    "color": "#E24B4A",
                    "desc": "To maintain tenable conditions during occupant evacuation, materials and assemblies must resist fire spread and limit generation of smoke, heat and toxic gases, appropriate to evacuation time, occupant number and mobility, building function and use, and any active fire safety systems. Applies to linings, materials and assemblies in Class 2–9 buildings.",
                    "example": "Wall and ceiling linings in a Class 6 shopping centre must have low spread-of-flame and low smoke development indices — materials that produce dense toxic smoke (like some foamed plastics) are prohibited as linings because they rapidly render escape routes untenable.",
                    "why": "Smoke inhalation kills more people than direct flame contact in building fires — lining material selection directly controls how quickly escape routes become life-threatening during a fire.",
                },
                {
                    "id": "C1-P5",
                    "title": "C1P5",
                    "subtitle": "Concrete external walls in fire",
                    "color": "#E24B4A",
                    "desc": "A concrete external wall that could collapse as a complete panel (e.g. tilt-up and precast concrete) must be designed so that in the event of fire within the building, the likelihood of outward collapse is avoided. Does not apply to buildings with more than two storeys above ground level.",
                    "example": "A single-storey tilt-up concrete warehouse must have its panels designed with connections and reinforcement details that prevent the wall panel falling outward onto firefighters operating outside the building during an internal fire.",
                    "why": "Tilt-up panels can fail catastrophically and fall outward as a single unit — firefighters positioned outside the building face lethal risk if panels collapse during fire attack operations.",
                },
                {
                    "id": "C1-P6",
                    "title": "C1P6",
                    "subtitle": "Fire protection of service equipment",
                    "color": "#E24B4A",
                    "desc": "A building must have elements that avoid spread of fire from service equipment having a high fire hazard or a potential for explosion resulting from a high fire hazard.",
                    "example": "A building plant room containing gas boilers (high fire hazard, explosion potential) must be enclosed in fire-rated construction to contain any fire or explosion within the plant room and prevent it spreading to the rest of the building.",
                    "why": "Service equipment with fuel sources or high thermal loads can trigger fires that spread rapidly — fire-rated enclosures provide containment at the source before suppression systems activate.",
                },
                {
                    "id": "C1-P7",
                    "title": "C1P7",
                    "subtitle": "Fire protection of emergency equipment",
                    "color": "#E24B4A",
                    "desc": "A building must have elements that avoid spread of fire so that emergency equipment will continue to operate for the period necessary to ensure its intended function is maintained during a fire.",
                    "example": "A fire pump room and emergency generator room must be enclosed in fire-rated construction — if the generator is needed to power emergency lighting and fire pumps, it must keep operating even while a fire burns elsewhere in the building.",
                    "why": "Emergency equipment is the last line of defence — if fire disables the fire pump, sprinkler system or emergency lighting before occupants evacuate, the consequences are catastrophic.",
                },
                {
                    "id": "C1-P8",
                    "title": "C1P8",
                    "subtitle": "Fire protection of openings and penetrations",
                    "color": "#E24B4A",
                    "desc": "Any building element provided to resist fire spread must be protected so that adequate performance is maintained where openings, construction joints and the like occur, and where penetrations occur for building services.",
                    "example": "A fire-rated wall between two tenancies must have every pipe, conduit and duct penetration sealed with a tested fire collar or intumescent system — an unsealed 50mm pipe penetration can allow fire and smoke to pass through a 2-hour fire wall within minutes.",
                    "why": "A fire-rated wall with unsealed penetrations provides no real fire resistance — penetration sealing is the most commonly failed element in fire-rated construction and the most common path for fire spread.",
                },
                {
                    "id": "C1-P9",
                    "title": "C1P9",
                    "subtitle": "Fire brigade access",
                    "color": "#E24B4A",
                    "desc": "Access must be provided to and around a building for fire brigade vehicles and personnel to facilitate fire brigade intervention appropriate to building function, fire load, fire intensity, fire hazard, active fire systems, and fire compartment size.",
                    "example": "A large Class 7 warehouse must have perimeter roads wide enough (minimum 4m clear width) for fire trucks to access all sides of the building, with overhead clearance for aerial appliances and hardstand areas for outriggers.",
                    "why": "Fire brigade vehicles cannot operate effectively without adequate access roads — a fire that reaches 100% of a building before firefighters can position equipment results in total loss and risk to personnel.",
                },
                # ── Verification Methods ───────────────────────────────────
                {
                    "id": "C1-V1",
                    "title": "C1V1",
                    "subtitle": "Fire spread between buildings on adjoining allotments",
                    "color": "#E24B4A",
                    "desc": "Compliance with C1P2(1)(c) is verified when it is calculated that a building will not cause heat flux exceeding the limits in Table C1V1 at the adjoining property boundary, and the building can withstand those heat flux levels without ignition.",
                    "example": "A new Class 6 building 2m from an allotment boundary undergoes fire engineering analysis. Calculations show the external wall radiates less than 10 kW/m² at the boundary and the facade can withstand that heat flux without igniting — C1V1 compliance is demonstrated.",
                    "why": "C1V1 is the performance pathway for buildings that cannot meet the prescriptive DTS separation distances — it allows fire engineering to demonstrate equivalent safety through heat flux calculations rather than fixed setback rules.",
                },
                {
                    "id": "C1-V2",
                    "title": "C1V2",
                    "subtitle": "Fire spread between buildings on the same allotment",
                    "color": "#E24B4A",
                    "desc": "Compliance with C1P2(1)(c) for buildings on the same allotment is verified when, for the distances between buildings, each building can withstand the heat flux limits in Table C1V2 without ignition and will not exceed those heat flux levels.",
                    "example": "Two warehouse buildings on the same industrial site are 6m apart. Fire engineering calculates mutual heat flux at that distance — if both buildings' facades can withstand the calculated flux without igniting, C1V2 is satisfied without requiring fire-rated walls.",
                    "why": "Buildings on the same allotment are often closer together than the prescriptive DTS rules allow — C1V2 provides the calculation-based alternative to demonstrate safe separation distance.",
                },
                {
                    "id": "C1-V3",
                    "title": "C1V3",
                    "subtitle": "Fire spread via external walls",
                    "color": "#E24B4A",
                    "standard": "AS 5113",
                    "desc": "Compliance with C1P2 for fire spread via external walls is verified when the external wall system has been tested per AS 5113 and achieved EW classification, with cavity barriers at each floor perimeter if the wall contains a cavity. Additional sprinkler requirements apply for Type A construction buildings, and for Type B construction the building must be Class 5–8 or a Class 2/3/9 building with sprinklers or compliant horizontal construction.",
                    "example": "A 12-storey Class 2 apartment building proposes an aluminium composite panel cladding system. The system must be tested to AS 5113 and achieve EW classification. As a Type A construction building, it must also be sprinkler-protected throughout with balcony sprinkler heads where overhead coverage is not achieved.",
                    "why": "External wall fire spread was responsible for the Grenfell Tower disaster — C1V3 was introduced to require actual fire testing of external wall systems rather than relying on individual material test results that do not reflect system behaviour.",
                },
                {
                    "id": "C1-V4",
                    "title": "C1V4",
                    "subtitle": "Fire Safety Verification Method",
                    "color": "#E24B4A",
                    "desc": "Compliance with C1P1 through C1P9 is verified when a building is designed in accordance with the Fire Safety Verification Method Standard. Requires a Performance-Based Design Brief (PBDB) involving all stakeholders, a documented fire strategy, demonstration that the proposed design provides at least equivalent safety to the DTS provisions, and a final report including all modelling and analysis.",
                    "example": "A unique mixed-use high-rise proposes an atrium design that cannot meet DTS compartmentation requirements. A fire safety engineer develops a PBDB with the client, architect, fire authority and building surveyor, models fire and evacuation scenarios, and demonstrates via C1V4 that the sprinkler and smoke control system provides equivalent safety to the DTS provisions.",
                    "why": "C1V4 is the comprehensive fire engineering pathway for complex buildings — it requires stakeholder agreement, documented fire strategy, and rigorous equivalency demonstration rather than allowing piecemeal departures from DTS without a holistic fire safety assessment.",
                },
                # ── DTS Provisions ────────────────────────────────────────
                {
                    "id": "C1-D1",
                    "title": "C1D1",
                    "subtitle": "Deemed-to-Satisfy provisions",
                    "color": "#E24B4A",
                    "desc": "Where a DTS Solution is proposed, Performance Requirements C1P1 to C1P9 are satisfied by complying with C1D2 to C1D19 and Parts C2, C3 and C4.",
                    "example": "A standard Class 5 office building follows the DTS pathway: Type B construction, fire resistance levels from Specification 1, fire compartment sizes from C3D3, exit protection from C4D3, and penetration sealing from Specification 13.",
                    "why": "C1D1 is the gateway clause for fire resistance DTS compliance — it maps all nine performance requirements to their corresponding DTS solutions across Parts C1–C4.",
                },
            ],
        },
        {
            "id": "C2",
            "title": "Part C2",
            "subtitle": "Fire resistance and stability",
            "color": "#E24B4A",
            "children": [
                {
                    "id": "C2-O",
                    "title": "C2O1",
                    "subtitle": "Objective",
                    "color": "#E24B4A",
                    "desc": "Covered by C1O1 — the objective of Parts C1–C4 is shared across all fire resistance parts.",
                },
                {
                    "id": "C2-P",
                    "title": "C2P1",
                    "subtitle": "Performance requirement",
                    "color": "#E24B4A",
                    "desc": "Covered by C1P1 and C1P2 — structural stability during fire and spread of fire performance requirements apply to Part C2 DTS provisions.",
                },
                {
                    "id": "C2-D",
                    "title": "C2D1–C2D12",
                    "subtitle": "DTS — Type A, B, C construction and FRL",
                    "color": "#E24B4A",
                    "desc": "Part C2 DTS provisions specify the type of fire-resisting construction required (Type A, B or C) based on building class and effective height, and the Fire Resistance Levels (FRL) required for structural elements. FRL is expressed as three numbers: structural adequacy/integrity/insulation in minutes (e.g. 120/120/120).",
                    "example": "A Class 2 apartment building of 4 storeys requires Type B construction. Loadbearing walls between apartments need FRL 60/60/60. A Class 5 office of 8 storeys requires Type A construction with loadbearing walls at FRL 120/120/120.",
                    "why": "Type of construction and FRL requirements are the primary tools for ensuring buildings remain structurally stable and fire does not spread during the evacuation and fire brigade intervention period.",
                },
            ],
        },
        {
            "id": "C3",
            "title": "Part C3",
            "subtitle": "Compartmentation and separation",
            "color": "#E24B4A",
            "children": [
                {
                    "id": "C3-O",
                    "title": "C3O1",
                    "subtitle": "Objective",
                    "color": "#E24B4A",
                    "desc": "Covered by C1O1 — the objective of Parts C1–C4 is shared.",
                },
                {
                    "id": "C3-P",
                    "title": "C3P1",
                    "subtitle": "Performance requirement",
                    "color": "#E24B4A",
                    "desc": "Covered by C1P2 — avoidance of fire spread within and between buildings.",
                },
                {
                    "id": "C3-D",
                    "title": "C3D1–C3D17",
                    "subtitle": "DTS — fire compartment sizes and separation",
                    "color": "#E24B4A",
                    "desc": "Part C3 DTS provisions specify maximum fire compartment sizes, separation requirements between different building classes and uses, protection of openings in fire walls, and requirements for vertical separation between floor levels to prevent fire spread via external wall cavities and floor/ceiling spaces.",
                    "example": "A Class 6 retail building has a maximum fire compartment floor area of 8000m² in a sprinklered building or 3500m² in a non-sprinklered building. A larger shopping centre must be divided into fire compartments by fire walls with FRL 240/240/240.",
                    "why": "Fire compartment size limits the amount of fuel available to a fire and the area over which it can spread before suppression — smaller compartments give firefighters a manageable fire to attack.",
                },
            ],
        },
        {
            "id": "C4",
            "title": "Part C4",
            "subtitle": "Protection of openings",
            "color": "#E24B4A",
            "children": [
                {
                    "id": "C4-O",
                    "title": "C4O1",
                    "subtitle": "Objective",
                    "color": "#E24B4A",
                    "desc": "Covered by C1O1 — the objective of Parts C1–C4 is shared.",
                },
                {
                    "id": "C4-P",
                    "title": "C4P1",
                    "subtitle": "Performance requirement",
                    "color": "#E24B4A",
                    "desc": "Covered by C1P8 — openings and penetrations in fire-rated elements must be protected to maintain adequate fire resistance performance.",
                },
                {
                    "id": "C4-D",
                    "title": "C4D1–C4D10",
                    "subtitle": "DTS — fire doors, windows, penetrations",
                    "color": "#E24B4A",
                    "standard": "Specification 12, Specification 13",
                    "desc": "Part C4 DTS provisions cover protection of openings in fire-rated walls and floors including fire doors (Specification 12), fire windows, service penetrations (Specification 13), construction joints, and duct penetrations. All fire doors must be tested and certified to the required FRL. All service penetrations must be sealed with tested fire collar or intumescent systems.",
                    "example": "A fire wall between two Class 6 tenancies requires FRL 120/120/120 construction. Any door opening must have a fire door tested to -/120/30 (integrity and insulation). Any plumbing penetration must have a tested fire collar maintaining the FRL of the wall.",
                    "why": "Openings are the weakest point in any fire-rated element — an unprotected door opening in a fire wall renders the entire wall ineffective. Penetration sealing is the most commonly deficient element found in fire safety audits.",
                },
            ],
        },
        {
            "id": "C-S5",
            "title": "Specification 5",
            "subtitle": "Fire-resisting construction",
            "color": "#E24B4A",
            "desc": "Detailed construction requirements for fire-resisting elements including walls, floors, columns and beams. Specifies concrete cover, steel protection, and other construction details needed to achieve the required FRL for each element type.",
            "example": "A concrete column required to achieve FRL 120/120/120 needs minimum 40mm concrete cover to the reinforcement. A steel column requires sprayed fire protection or an encasement system tested to achieve the required FRL.",
            "why": "FRL is achieved through specific construction details — the cover to reinforcement in concrete directly controls how long the steel remains below its critical temperature during fire.",
        },
        {
            "id": "C-S6",
            "title": "Specification 6",
            "subtitle": "Structural tests for lightweight construction",
            "color": "#E24B4A",
            "desc": "Test methods for determining the fire resistance of lightweight construction elements such as steel stud and plasterboard wall systems, suspended ceiling systems, and other non-masonry/concrete assemblies.",
            "example": "A steel stud wall with two layers of 13mm fire-rated plasterboard each side must be tested to Specification 6 to confirm it achieves FRL 60/60/60. The test exposes one face to a standard fire curve and measures structural adequacy, integrity and insulation over time.",
            "why": "Lightweight systems cannot rely on the mass and thermal inertia of concrete and masonry — fire resistance must be demonstrated by testing the complete assembled system rather than calculated from individual material properties.",
        },
        {
            "id": "C-S7",
            "title": "Specification 7",
            "subtitle": "Fire hazard properties",
            "color": "#E24B4A",
            "desc": "Specifies fire hazard properties including ignitability, spread of flame, smoke developed index and heat evolved index for materials used as linings, insulation and other applications in buildings. Materials must meet the Group Number requirements appropriate to their location and building class.",
            "example": "Wall linings in the exit corridor of a Class 5 office building must be Group 1 materials (lowest fire hazard). A PIR insulation product used as a wall lining must have a tested Group Number — if it is Group 3 or 4, it cannot be used as an exposed lining in that location.",
            "why": "Lining material selection is the primary control over how quickly a fire grows and how much toxic smoke is produced — Group Number requirements prevent high-hazard materials being used in locations where rapid fire growth would trap occupants.",
        },
        {
            "id": "C-S8",
            "title": "Specification 8",
            "subtitle": "Performance of external walls in fire",
            "color": "#E24B4A",
            "standard": "AS 5113",
            "desc": "Requirements for external wall systems to resist fire spread. Systems must be tested to AS 5113 and achieve EW classification. Relevant to cladding product selection — non-combustible or EW-classified cladding systems required on buildings of Type A and B construction above certain heights.",
            "example": "An aluminium composite panel (ACP) cladding system on a Class 2 building of 4 storeys must be tested as a complete system to AS 5113. A product with a polyethylene core that achieves EW classification in the specific system configuration may be used — the same product in a different system configuration may not achieve EW.",
            "why": "Individual material non-combustibility tests do not predict system behaviour — Grenfell Tower used ACPs that individually passed material tests but the installed system spread fire catastrophically. AS 5113 tests the complete installed system.",
        },
        {
            "id": "C-S9",
            "title": "Specification 9",
            "subtitle": "Cavity barriers for fire-protected timber",
            "color": "#E24B4A",
            "desc": "Specifies cavity barrier requirements within fire-protected timber construction systems to prevent fire spreading through concealed cavities in wall and floor assemblies.",
            "example": "A fire-protected timber frame wall system with a concealed cavity between the plasterboard lining and the timber frame must have cavity barriers at each floor level and at maximum 20m horizontal intervals to prevent fire racing through the cavity and bypassing the fire-rated lining.",
            "why": "Concealed cavities act as chimneys — fire can travel through them far faster than through the rated construction, defeating the purpose of the fire-rated assembly if barriers are not installed.",
        },
        {
            "id": "C-S10",
            "title": "Specification 10",
            "subtitle": "Fire-protected timber",
            "color": "#E24B4A",
            "desc": "Requirements for timber elements used in fire-resistance rated construction. Specifies the char rate of timber and the additional section size required to maintain structural adequacy for the required FRL period after the outer char layer forms.",
            "example": "A glulam timber beam required to achieve FRL 60/-/- (structural adequacy only) must have sufficient additional timber section beyond the structurally required size to allow for 60 minutes of charring at the standard char rate without the remaining timber section falling below the required structural capacity.",
            "why": "Timber chars at a predictable rate — the char layer actually insulates the inner timber and slows further burning. Specification 10 exploits this behaviour to allow exposed timber in fire-rated construction by oversizing the section.",
        },
        {
            "id": "C-S11",
            "title": "Specification 11",
            "subtitle": "Smoke-proof walls in health-care and residential care buildings",
            "color": "#E24B4A",
            "desc": "Construction requirements for smoke-proof walls in Class 9a health-care buildings and Class 9c residential care buildings. Covers wall construction, door sealing, and gap control to limit smoke transfer between patient care areas and corridors.",
            "example": "A smoke-proof wall in a hospital ward must have all gaps sealed, doors fitted with smoke seals on all four sides, and penetrations fully sealed — the wall is not required to have a full FRL but must limit smoke leakage to allow horizontal evacuation of patients.",
            "why": "In hospital and aged care facilities, patients cannot use stairs — the defend-in-place strategy requires smoke containment to allow horizontal evacuation to an adjacent smoke compartment rather than vertical evacuation.",
        },
        {
            "id": "C-S12",
            "title": "Specification 12",
            "subtitle": "Fire doors, smoke doors, fire windows and shutters",
            "color": "#E24B4A",
            "desc": "Specifies construction and performance requirements for fire doors, smoke doors, fire windows and shutters. All fire doors must be tested and listed. Covers hardware requirements including self-closing devices, positive latching, and hold-open devices with automatic release.",
            "example": "A fire door in a Class 2 apartment building corridor must be a listed fire door assembly achieving the required FRL, fitted with a self-closing device, positive latching hardware, and intumescent seals. It must not be propped open — hold-open devices must release automatically on smoke detection.",
            "why": "A fire door left propped open provides zero fire resistance — self-closing and automatic release requirements ensure fire doors are in the closed position when they are needed during a fire.",
        },
        {
            "id": "C-S13",
            "title": "Specification 13",
            "subtitle": "Penetration of walls, floors and ceilings by services",
            "color": "#E24B4A",
            "standard": "AS 4072.1",
            "desc": "Specifies how service penetrations through fire-rated elements must be sealed. Fire collars, intumescent wraps, and other tested systems must be installed to maintain the FRL of the penetrated element. Each penetration system must be tested for the specific pipe material, size and wall construction combination.",
            "example": "A 100mm uPVC drain pipe penetrating a 2-hour fire-rated concrete floor slab must have a tested intumescent fire collar installed at the slab soffit. When exposed to fire, the intumescent material expands and crushes the melting plastic pipe, sealing the opening before fire can pass through.",
            "why": "PVC and other plastic pipes melt and disappear in a fire, leaving an open hole in a fire-rated floor — intumescent collars are the product solution that maintains floor fire resistance despite the presence of plastic service penetrations.",
        },
    ],
}
