SECTION_F = {
    "id": "F",
    "title": "Section F",
    "subtitle": "Health and amenity",
    "color": "#1D9E75",
    "children": [
        {
            "id": "F1",
            "title": "Part F1",
            "subtitle": "Surface water",
            "color": "#1D9E75",
            "children": [
                {
                    "id": "F1-O",
                    "title": "F1O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "F1-P",
                    "title": "F1P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                },
                {
                    "id": "F1-D",
                    "title": "F1D1",
                    "subtitle": "DTS → AS 4654.2",
                    "color": "#1D9E75",
                    "standard": "AS 4654.2",
                    "children": [
                        {
                            "id": "F1-AS",
                            "title": "AS 4654.2",
                            "subtitle": "Waterproofing — external above-ground",
                            "color": "#06b6d4",
                            "desc": "Covers waterproofing membranes for external above-ground surfaces such as balconies and podiums. Membrane must extend minimum 100mm up vertical faces. All penetrations must be fully detailed.",
                        },
                    ],
                },
            ],
        },
        {
            "id": "F2",
            "title": "Part F2",
            "subtitle": "Wet areas",
            "color": "#1D9E75",
            "bss": True,
            "children": [
                {
                    "id": "F2-O",
                    "title": "F2O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                    "desc": "Minimise risk of water from wet areas causing damage or unhealthy conditions.",
                },
                {
                    "id": "F2-F",
                    "title": "F2F1, F2F2",
                    "subtitle": "Functional statements",
                    "color": "#1D9E75",
                    "desc": "Building must protect against water damage and overflow from bathrooms and laundries.",
                },
                {
                    "id": "F2-P",
                    "title": "F2P1, F2P2",
                    "subtitle": "Performance requirements",
                    "color": "#1D9E75",
                    "desc": "Overflow from bathrooms must be prevented from reaching other units or public spaces.",
                },
                {
                    "id": "F2-D",
                    "title": "F2D1 → F2D2",
                    "subtitle": "DTS → AS 3740",
                    "color": "#1D9E75",
                    "standard": "AS 3740, AS 2588",
                    "desc": "Building elements in wet areas must be waterproof per Specification 26 and comply with AS 3740.",
                    "children": [
                        {
                            "id": "F2-AS1",
                            "title": "AS 3740",
                            "subtitle": "Waterproofing of domestic wet areas",
                            "color": "#06b6d4",
                            "desc": "Zone 1: shower recess floor and walls to 1800mm. Zone 2: bathroom floor with 150mm upstand at walls. Products must be compatible with substrate and applied by a licensed waterproofer.",
                        },
                        {
                            "id": "F2-AS2",
                            "title": "AS 2588",
                            "subtitle": "Gypsum plasterboard",
                            "color": "#06b6d4",
                            "desc": "Moisture-resistant (MR) plasterboard required in wet areas. Fire-rated board required on FRL walls. Standard board for dry areas only.",
                        },
                    ],
                },
            ],
        },
        {
            "id": "F3",
            "title": "Part F3",
            "subtitle": "Roof and wall cladding",
            "color": "#1D9E75",
            "bss": True,
            "children": [
                {
                    "id": "F3-O",
                    "title": "F3O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "F3-P",
                    "title": "F3P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                },
                {
                    "id": "F3-D",
                    "title": "F3D1",
                    "subtitle": "DTS → AS 1288, AS 2047",
                    "color": "#1D9E75",
                    "standard": "AS 1288, AS 2047",
                    "children": [
                        {
                            "id": "F3-AS1",
                            "title": "AS 1288:2021",
                            "subtitle": "Glass in buildings",
                            "color": "#06b6d4",
                            "desc": "Safety glass required in shower screens, near doors, and low-level glazing below 300mm from floor. Minimum 6mm toughened safety glass for shower screens. Laminated glass for overhead glazing.",
                        },
                        {
                            "id": "F3-AS2",
                            "title": "AS 2047:2014",
                            "subtitle": "Windows and external glazed doors",
                            "color": "#06b6d4",
                            "desc": "Windows and external glazed doors must meet structural and weather performance ratings for the wind region. Performance levels N1 to N6. Products must be tested and rated to AS 2047.",
                        },
                    ],
                },
            ],
        },
        {
            "id": "F4",
            "title": "Part F4",
            "subtitle": "Sanitary and other facilities",
            "color": "#1D9E75",
            "children": [
                {
                    "id": "F4-O",
                    "title": "F4O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "F4-P",
                    "title": "F4P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                },
                {
                    "id": "F4-D",
                    "title": "F4D1",
                    "subtitle": "DTS solution",
                    "color": "#1D9E75",
                    "desc": "Specifies minimum number of toilets, basins, and showers based on building class and occupancy numbers.",
                },
            ],
        },
        {
            "id": "F5",
            "title": "Part F5",
            "subtitle": "Room heights",
            "color": "#1D9E75",
            "bss": True,
            "children": [
                {
                    "id": "F5-O",
                    "title": "F5O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "F5-P",
                    "title": "F5P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                },
                {
                    "id": "F5-D",
                    "title": "F5D2",
                    "subtitle": "DTS → 2.4m minimum",
                    "color": "#1D9E75",
                    "desc": "Habitable rooms must have a minimum ceiling height of 2.4m.",
                },
            ],
        },
        {
            "id": "F6",
            "title": "Part F6",
            "subtitle": "Light and ventilation",
            "color": "#1D9E75",
            "bss": True,
            "children": [
                {
                    "id": "F6-O",
                    "title": "F6O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "F6-P",
                    "title": "F6P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                },
                {
                    "id": "F6-D",
                    "title": "F6D2–F6D3",
                    "subtitle": "DTS → window area ratios",
                    "color": "#1D9E75",
                    "desc": "Natural light must be provided to all habitable rooms (Class 2, 4), bedrooms and dormitories (Class 3), sleeping rooms (Class 9a, 9c), and general purpose classrooms and playrooms (Class 9b). Required natural light must be provided by windows with aggregate light-transmitting area not less than 10% of floor area, or roof lights with not less than 3% of floor area, or a proportional combination of both.",
                    "example": "A 20m² bedroom in a Class 2 apartment requires windows with a minimum light-transmitting area of 2m² (10% of 20m²). If roof lights are used instead, minimum 0.6m² (3% of 20m²). A combination of 1m² window and 0.3m² roof light also satisfies the requirement.",
                    "why": "Natural light is essential for occupant health and wellbeing — the 10% window-to-floor ratio is the minimum that provides meaningful daylight to a habitable room under typical Australian sky conditions.",
                    "calculator_type": "window_ratio",
                },
                {
                    "id": "F6-V3",
                    "title": "F6V3",
                    "subtitle": "Verification — average daylight factor",
                    "color": "#1D9E75",
                    "desc": "Compliance with F6P1 (2% average daylight factor) is verified using the formula: DF = W·T·θ / (A·(1−R²)) × 100%, where W = net window area (m²), A = total internal surface area (m²), T = diffuse light transmittance of window, θ = visible sky angle in degrees, R = area-weighted average reflectance. Applies to habitable rooms in Class 2/4, bedrooms in Class 3, sleeping rooms in Class 9a/9c, and classrooms/playrooms in Class 9b.",
                    "example": "A bedroom 4m × 5m × 2.7m high has a single window W=1.8m², total internal surface area A=74m², glass transmittance T=0.7, sky angle θ=30°, average reflectance R=0.5. Use the daylight factor calculator below to check if DF ≥ 2%.",
                    "why": "F6V3 is the performance pathway for rooms where the DTS 10% window ratio cannot be met — it allows the designer to demonstrate equivalent natural light through calculation rather than a fixed ratio rule.",
                    "calculator_type": "daylight_factor",
                },
            ],
        },
        {
            "id": "F7",
            "title": "Part F7",
            "subtitle": "Sound transmission and insulation",
            "color": "#1D9E75",
            "children": [
                {
                    "id": "F7-O",
                    "title": "F7O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                    "desc": "To safeguard occupants from illness or loss of amenity from undue sound transmitted between adjoining sole-occupancy units, from common spaces to sole-occupancy units, and from parts of different classifications to sole-occupancy units. Applies only to Class 2, 3 and 9c buildings.",
                    "example": "Residents in a Class 2 apartment building must not be disturbed by noise from adjoining apartments, from the common corridor, or from a gym or commercial tenancy in the same building.",
                    "why": "Noise is one of the most common complaints in apartment buildings — inadequate sound insulation between units directly causes loss of amenity and can have serious health impacts including sleep deprivation and stress.",
                },
                {
                    "id": "F7-P1",
                    "title": "F7P1–F7P2",
                    "subtitle": "Performance requirements — Class 2 and 3",
                    "color": "#1D9E75",
                    "desc": "Floors separating sole-occupancy units or a SOC unit from plant rooms, lift shafts, stairways, corridors or different classifications must achieve: airborne DnT,w + Ctr ≥ 45, impact LnT,w ≤ 62. Walls between SOC units: DnT,w + Ctr ≥ 45 airborne. Walls from SOC unit to plant room/corridor/lift/different class: DnT,w ≥ 45. Door assemblies to corridor/lobby/stairway: DnT,w ≥ 25. Wet area walls between adjacent SOC units must also provide impact sound insulation.",
                    "example": "A floor between two Class 2 apartments must be tested in-situ and achieve DnT,w + Ctr ≥ 45 for airborne sound and LnT,w ≤ 62 for impact sound. These are in-situ measurements — they are lower than the laboratory Rw values due to flanking transmission through the building structure.",
                    "why": "In-situ DnT,w values are typically 5–8dB lower than laboratory Rw values because sound flanks around the separating element through connected structure — the performance requirement accounts for this by using in-situ measurement standards.",
                },
                {
                    "id": "F7-D5",
                    "title": "F7D5–F7D6",
                    "subtitle": "DTS — Rw+Ctr ratings for floors and walls",
                    "color": "#1D9E75",
                    "standard": "Specification 28, AS/NZS ISO 717.1",
                    "desc": "DTS ratings (laboratory Rw values) are higher than performance requirement in-situ values to account for flanking. Class 2/3 floors between SOC units: Rw+Ctr ≥ 50 airborne, Ln,w ≤ 62 impact. Class 2/3 walls between SOC units: Rw+Ctr ≥ 50. Walls from SOC unit to plant room/corridor/lift/different class: Rw ≥ 50. Door to corridor/lobby: Rw ≥ 30. Wet area walls between SOC units: discontinuous construction required. Class 9c walls and floors: Rw ≥ 45. Services pipes adjacent to habitable rooms: Rw+Ctr ≥ 40. Services adjacent to kitchens/non-habitable: Rw+Ctr ≥ 25.",
                    "example": "A wall between two Class 2 apartments must achieve laboratory Rw+Ctr ≥ 50. A standard 90mm steel stud wall with one layer of 13mm plasterboard each side achieves approximately Rw+Ctr 38 — insufficient. Double stud with acoustic batts and two layers of plasterboard each side typically achieves Rw+Ctr 52–55.",
                    "why": "The DTS Rw+Ctr ≥ 50 requirement is set 5dB above the performance requirement DnT,w+Ctr ≥ 45 to ensure that after flanking transmission reduces in-situ performance, the minimum performance requirement is still met.",
                    "calculator_type": "rw_checker",
                },
                {
                    "id": "F7-D7",
                    "title": "F7D7–F7D8",
                    "subtitle": "DTS — services and pumps",
                    "color": "#1D9E75",
                    "standard": "Specification 28",
                    "desc": "Ducts and pipes serving or passing through more than one sole-occupancy unit must be separated from habitable rooms (not kitchen) by construction with Rw+Ctr ≥ 40, and from kitchens or non-habitable rooms by Rw+Ctr ≥ 25. Stormwater pipes passing through a SOC unit follow the same requirements. Circulating and other pumps must use flexible couplings at the point of connection to service pipes.",
                    "example": "A common sewer riser passing through the wall of a Class 2 apartment adjacent to a bedroom must be enclosed in a duct or boxing with Rw+Ctr ≥ 40 — typically a double layer of 13mm plasterboard on a steel stud frame with acoustic sealant at all junctions. A pump in a plant room must have flexible hose connections to all pipework to prevent vibration transmitting through the pipes to the structure.",
                    "why": "Pipe noise and pump vibration are the most common sources of acoustic complaints in apartment buildings after party wall sound — the services requirements and flexible coupling mandate address the two most significant mechanical noise transmission paths.",
                },
                {
                    "id": "F7-S28",
                    "title": "Specification 28",
                    "subtitle": "Sound insulation for building elements",
                    "color": "#1D9E75",
                    "standard": "AS/NZS ISO 717.1, AS ISO 717.2",
                    "desc": "Specification 28 lists prescriptive wall and floor constructions that are deemed to achieve the required Rw or Rw+Ctr ratings without laboratory testing. Constructions are listed by type (masonry, concrete, lightweight framed) with their deemed Rw values. Using a listed system avoids the need for laboratory acoustic testing of the specific assembly.",
                    "example": "A 200mm reinforced concrete floor is listed in Specification 28 as achieving Rw+Ctr 54 — a designer can specify this floor type for a Class 2 building without commissioning acoustic laboratory testing, as it is deemed to achieve the required Rw+Ctr ≥ 50.",
                    "why": "Laboratory acoustic testing of every wall and floor type would be prohibitively expensive for standard construction — Specification 28 provides pre-tested deemed-to-satisfy constructions so designers can select compliant systems from a table rather than requiring bespoke testing for common assemblies.",
                },
                {
                    "id": "F7-S29",
                    "title": "Specification 29",
                    "subtitle": "Impact sound — test of equivalence",
                    "color": "#1D9E75",
                    "desc": "Defines the test methodology for demonstrating equivalence of impact sound performance in floor assemblies, particularly for Class 9c buildings. Allows alternative floor constructions to be accepted if they perform no worse than a listed Specification 28 system in comparative impact sound testing.",
                    "example": "A Class 9c building proposes a floating timber floor system not listed in Specification 28. The system can be tested per Specification 29 and compared against a listed concrete floor system — if it performs equally or better for impact sound, it is accepted as equivalent.",
                    "why": "Specification 29 provides the performance pathway for impact sound in Class 9c buildings where prescriptive Specification 28 systems may not be suitable for aged care environments that need soft, non-slip flooring rather than hard concrete.",
                },
            ],
        },
        {
            "id": "F8",
            "title": "Part F8",
            "subtitle": "Condensation management",
            "color": "#1D9E75",
            "children": [
                {
                    "id": "F8-O",
                    "title": "F8O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "F8-P",
                    "title": "F8P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                },
                {
                    "id": "F8-D",
                    "title": "F8D1",
                    "subtitle": "DTS solution",
                    "color": "#1D9E75",
                    "desc": "Requires vapour barriers, ventilated roof spaces, and exhaust fans ducted to outside in climate zones prone to condensation.",
                },
            ],
        },
        {
            "id": "F-S26",
            "title": "Specification 26",
            "subtitle": "Waterproofing requirements for wet areas",
            "color": "#1D9E75",
            "desc": "Detailed table of waterproofing zones, materials, and minimum membrane heights for all wet area locations including showers, bathrooms, laundries, and balconies.",
        },
        {
            "id": "F-S27",
            "title": "Specification 27",
            "subtitle": "Accessible adult change facilities",
            "color": "#1D9E75",
            "desc": "Layout and fitout requirements for accessible adult change facilities in Class 9 buildings. Covers floor area, hoist provisions, bed dimensions and privacy screens.",
        },
        {
            "id": "F-S28",
            "title": "Specification 28",
            "subtitle": "Sound insulation for building elements",
            "color": "#1D9E75",
            "desc": "Prescribes minimum Rw+Ctr ratings for walls and floors between sole-occupancy units and adjoining spaces. Key reference for wall and floor system product selection in Class 2 and 3 buildings.",
        },
        {
            "id": "F-S29",
            "title": "Specification 29",
            "subtitle": "Impact sound — test of equivalence",
            "color": "#1D9E75",
            "desc": "Defines test methodology for demonstrating equivalence of impact sound performance in floor assemblies. Relevant to flooring product selection between apartments.",
        },
    ],
}
