V2_SECTION_H = {
    "id": "V2-H",
    "title": "Section H",
    "subtitle": "Class 1 and 10 buildings",
    "color": "#06b6d4",
    "children": [
        {
            "id": "V2-H1",
            "title": "Part H1",
            "subtitle": "Structure",
            "color": "#06b6d4",
            "children": [
                {
                    "id": "V2-H1-O",
                    "title": "H1O1",
                    "subtitle": "Objective",
                    "color": "#06b6d4",
                },
                {
                    "id": "V2-H1-P",
                    "title": "H1P1",
                    "subtitle": "Performance requirement",
                    "color": "#06b6d4",
                },
                {
                    "id": "V2-H1-D",
                    "title": "H1D1",
                    "subtitle": "DTS solution",
                    "color": "#06b6d4",
                },
            ],
        },
        {
            "id": "V2-H2",
            "title": "Part H2",
            "subtitle": "Damp and weatherproofing",
            "color": "#06b6d4",
            "children": [
                {
                    "id": "V2-H2-O",
                    "title": "H2O1",
                    "subtitle": "Objective",
                    "color": "#06b6d4",
                },
                {
                    "id": "V2-H2-P",
                    "title": "H2P1",
                    "subtitle": "Performance requirement",
                    "color": "#06b6d4",
                },
                {
                    "id": "V2-H2-D",
                    "title": "H2D1",
                    "subtitle": "DTS → AS 4654.2",
                    "color": "#06b6d4",
                    "standard": "AS 4654.2",
                    "children": [
                        {
                            "id": "V2-H2-AS",
                            "title": "AS 4654.2",
                            "subtitle": "External waterproofing membranes",
                            "color": "#1D9E75",
                            "desc": "Waterproofing membranes for external above-ground surfaces — balconies, podiums. Membrane must extend minimum 100mm up vertical faces.",
                        },
                    ],
                },
            ],
        },
        {
            "id": "V2-H3",
            "title": "Part H3",
            "subtitle": "Fire safety",
            "color": "#E24B4A",
            "children": [
                {
                    "id": "V2-H3-O",
                    "title": "H3O1",
                    "subtitle": "Objective",
                    "color": "#E24B4A",
                },
                {
                    "id": "V2-H3-P",
                    "title": "H3P1",
                    "subtitle": "Performance requirement",
                    "color": "#E24B4A",
                },
                {
                    "id": "V2-H3-D",
                    "title": "H3D1",
                    "subtitle": "DTS solution",
                    "color": "#E24B4A",
                },
            ],
        },
        {
            "id": "V2-H4",
            "title": "Part H4",
            "subtitle": "Health and amenity",
            "color": "#1D9E75",
            "children": [
                {
                    "id": "V2-H4-O",
                    "title": "H4O1",
                    "subtitle": "Objective",
                    "color": "#1D9E75",
                },
                {
                    "id": "V2-H4-P",
                    "title": "H4P1",
                    "subtitle": "Performance requirement",
                    "color": "#1D9E75",
                    "desc": "Wet areas must be waterproofed to prevent water damage and health risks.",
                },
                {
                    "id": "V2-H4-D2",
                    "title": "H4D2",
                    "subtitle": "DTS → wet area locations",
                    "color": "#1D9E75",
                    "desc": "Specifies where waterproofing is required — shower recess, bathroom floor, laundry.",
                },
                {
                    "id": "V2-H4-D3",
                    "title": "H4D3",
                    "subtitle": "DTS → AS 3740",
                    "color": "#1D9E75",
                    "standard": "AS 3740, AS 2588",
                    "desc": "Specifies materials and installation method for waterproofing. References AS 3740.",
                    "children": [
                        {
                            "id": "V2-H4-AS1",
                            "title": "AS 3740",
                            "subtitle": "Waterproofing of wet areas",
                            "color": "#1D9E75",
                            "desc": "Zone 1: shower walls to 1800mm. Zone 2: bathroom floor with 150mm upstand at walls.",
                        },
                        {
                            "id": "V2-H4-AS2",
                            "title": "AS 2588",
                            "subtitle": "Gypsum plasterboard",
                            "color": "#1D9E75",
                            "desc": "Moisture-resistant plasterboard required in wet areas. Fire-rated board for FRL walls.",
                        },
                    ],
                },
            ],
        },
        {
            "id": "V2-H5",
            "title": "Part H5",
            "subtitle": "Safe movement and access",
            "color": "#378ADD",
            "children": [
                {
                    "id": "V2-H5-O",
                    "title": "H5O1",
                    "subtitle": "Objective",
                    "color": "#378ADD",
                },
                {
                    "id": "V2-H5-P",
                    "title": "H5P1",
                    "subtitle": "Performance requirement",
                    "color": "#378ADD",
                },
                {
                    "id": "V2-H5-D",
                    "title": "H5D1",
                    "subtitle": "DTS → stairs and balustrades",
                    "color": "#378ADD",
                    "desc": "Minimum stair dimensions, balustrade heights (1m for floors over 1m above ground), slip resistance.",
                },
            ],
        },
        {
            "id": "V2-H6",
            "title": "Part H6",
            "subtitle": "Energy efficiency",
            "color": "#BA7517",
            "children": [
                {
                    "id": "V2-H6-O",
                    "title": "H6O1",
                    "subtitle": "Objective",
                    "color": "#BA7517",
                },
                {
                    "id": "V2-H6-P",
                    "title": "H6P1",
                    "subtitle": "Performance requirement",
                    "color": "#BA7517",
                },
                {
                    "id": "V2-H6-D",
                    "title": "H6D1",
                    "subtitle": "DTS → AS 4859.1",
                    "color": "#BA7517",
                    "standard": "AS 4859.1",
                    "desc": "Minimum R-values for walls, roofs, and floors. Brisbane (Zone 2): R2.5 ceiling, R1.5 wall.",
                    "children": [
                        {
                            "id": "V2-H6-AS",
                            "title": "AS 4859.1",
                            "subtitle": "Thermal insulation materials",
                            "color": "#BA7517",
                            "desc": "R-value measures resistance to heat flow. Higher R-value = better insulation. Brisbane Zone 2 minimum: R2.5 ceiling, R1.5 wall.",
                        },
                    ],
                },
            ],
        },
        {
            "id": "V2-H7",
            "title": "Part H7",
            "subtitle": "Ancillary provisions",
            "color": "#888780",
            "children": [
                {
                    "id": "V2-H7-O",
                    "title": "H7O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "V2-H7-D",
                    "title": "H7D1",
                    "subtitle": "DTS solution",
                    "color": "#888780",
                },
            ],
        },
        {
            "id": "V2-H8",
            "title": "Part H8",
            "subtitle": "Livable housing design",
            "color": "#888780",
            "children": [
                {
                    "id": "V2-H8-O",
                    "title": "H8O1",
                    "subtitle": "Objective",
                    "color": "#888780",
                },
                {
                    "id": "V2-H8-P",
                    "title": "H8P1",
                    "subtitle": "Performance requirement",
                    "color": "#888780",
                },
                {
                    "id": "V2-H8-D",
                    "title": "H8D1",
                    "subtitle": "DTS → livable housing",
                    "color": "#888780",
                    "desc": "Accessible entry, step-free shower, wider doorways for livable housing design.",
                },
            ],
        },
    ],
}
